- src/main/java/ohsoontaxi/backend/domain/user/domain/User.java
> :art:: User Entity 수정 (#2)

- src/main/java/ohsoontaxi/backend/domain/participation/domain/Participation.java
- src/main/java/ohsoontaxi/backend/domain/participation/domain/vo/ParticipationInfoVo.java
- src/main/java/ohsoontaxi/backend/global/common/participation/SeatPosition.java
- Participation Entity 수정
- SeatPosition 생성
- ParticipationInfoVo 생성
> :art:: Participation 수정 (#3)

- src/main/java/ohsoontaxi/backend/domain/user/domain/User.java
- src/main/java/ohsoontaxi/backend/global/common/user/Gender.java
- User Entity 수정
- Enum Gender 생성
> :art:: User Entity 수정 (#4)

- src/main/java/ohsoontaxi/backend/domain/reservation/domain/Reservation.java
- src/main/java/ohsoontaxi/backend/domain/reservation/exception/NotHostException.java
- src/main/java/ohsoontaxi/backend/global/common/reservation/ReservationStatus.java
- src/main/java/ohsoontaxi/backend/global/common/user/Gender.java
- src/main/java/ohsoontaxi/backend/global/error/exception/ErrorCode.java
- src/main/resources/application.yml
- reservation 예외추가
- reservationStatus enum 생성
- Gender enum 수정
- errorcode 메세지 수정
- yml show-sql 주석 처리
> :art:: Reservation 수정 (#5)

- src/main/java/ohsoontaxi/backend/domain/participation/domain/Participation.java
- src/main/java/ohsoontaxi/backend/domain/participation/exception/NotHostException.java
- src/main/java/ohsoontaxi/backend/global/common/user/Gender.java
- Participation 예외처리 생성
- Participation 연관관계 메서드 수정 
- Gender 수정
> :art:: Participation 수정 (#6)

- src/main/java/ohsoontaxi/backend/domain/report/domain/Report.java
- src/main/java/ohsoontaxi/backend/domain/temperature/domain/Temperature.java
- Report Entity 수정
- Temperature Entity 수정
> :art:: Report, Temperature 수정 (#7)

- src/main/java/ohsoontaxi/backend/domain/report/domain/vo/ReportInfoVo.java
- src/main/java/ohsoontaxi/backend/global/common/report/ProcessingStatus.java
- ReportInfoVo 생성
- ProcessingStatus 생성
> :page_facing_up:: ReportInfoVo, ProcessingStatus 생성 (#8)

- src/main/java/ohsoontaxi/backend/domain/participation/domain/Participation.java
- src/main/java/ohsoontaxi/backend/domain/participation/domain/vo/ParticipationInfoVo.java
- src/main/java/ohsoontaxi/backend/domain/reservation/domain/Reservation.java
- src/main/java/ohsoontaxi/backend/domain/reservation/domain/vo/ReservationBaseInfoVo.java
- src/main/java/ohsoontaxi/backend/domain/reservation/presentation/ReservationController.java
- src/main/java/ohsoontaxi/backend/domain/reservation/presentation/dto/request/CreateReservationRequest.java
- src/main/java/ohsoontaxi/backend/domain/reservation/presentation/dto/response/ParticipationInfoDto.java
- src/main/java/ohsoontaxi/backend/domain/reservation/presentation/dto/response/ReservationResponse.java
- src/main/java/ohsoontaxi/backend/domain/reservation/service/ReservationService.java
- src/main/java/ohsoontaxi/backend/domain/user/domain/User.java
- src/main/java/ohsoontaxi/backend/domain/user/domain/vo/UserInfoVO.java
- ReservationResponse 생성
- userVO 생성
-  ParticipationVO에 userVO 추가
-  방 생성 기능 구현
> ✨: 방 생성 기능 추가 (#10)

- src/main/java/ohsoontaxi/backend/domain/credential/presentation/CredentialController.java
- src/main/java/ohsoontaxi/backend/domain/credential/service/CredentialService.java
> :art:: Login 수정 (#11)

- src/main/java/ohsoontaxi/backend/domain/credential/presentation/dto/response/AccessTokenDto.java
> :art:: Login 수정 (#12)

- src/main/java/ohsoontaxi/backend/domain/reservation/domain/Reservation.java
- src/main/java/ohsoontaxi/backend/domain/reservation/domain/repository/ReservationRepository.java
- src/main/java/ohsoontaxi/backend/domain/reservation/exception/ReservationNotFoundException.java
- src/main/java/ohsoontaxi/backend/domain/reservation/presentation/ReservationController.java
- src/main/java/ohsoontaxi/backend/domain/reservation/presentation/dto/request/UpdateReservationRequest.java
- src/main/java/ohsoontaxi/backend/domain/reservation/presentation/dto/response/ReservationBriefInfoDto.java
- src/main/java/ohsoontaxi/backend/domain/reservation/presentation/dto/response/ReservationResponse.java
- src/main/java/ohsoontaxi/backend/domain/reservation/service/ReservationService.java
- src/main/java/ohsoontaxi/backend/domain/reservation/service/ReservationUtils.java
- src/main/java/ohsoontaxi/backend/domain/reservation/service/dto/UpdateReservationDto.java
- src/main/java/ohsoontaxi/backend/global/error/exception/ErrorCode.java
- src/main/java/ohsoontaxi/backend/global/successresponse/SuccessResponseAdvice.java
-  방 삭제 , 업데이트, 상세 구현
-  ReservationUtills 생성
> ✨: 방 삭제, 업데이트, 상세, 구현 (#14)

- src/main/java/ohsoontaxi/backend/domain/participation/exception/ParticipationNotFoundException.java
- src/main/java/ohsoontaxi/backend/domain/participation/presentation/dto/request/CreateParticipationRequest.java
- src/main/java/ohsoontaxi/backend/domain/participation/presentation/dto/response/ParticipationResponse.java
- src/main/java/ohsoontaxi/backend/domain/participation/service/ParticipationService.java
- src/main/java/ohsoontaxi/backend/domain/participation/service/ParticipationUtils.java
- src/main/java/ohsoontaxi/backend/domain/report/exception/ReportNotFoundException.java
- src/main/java/ohsoontaxi/backend/domain/report/presentation/dto/request/CreateReportRequest.java
- src/main/java/ohsoontaxi/backend/domain/report/presentation/dto/request/UpdateProcessingStatusRequest.java
- src/main/java/ohsoontaxi/backend/domain/report/presentation/dto/response/ReportResponse.java
- src/main/java/ohsoontaxi/backend/domain/report/service/ReportService.java
- src/main/java/ohsoontaxi/backend/domain/report/service/ReportUtils.java
- src/main/java/ohsoontaxi/backend/domain/temperature/domain/repository/TemperatureRepository.java
- src/main/java/ohsoontaxi/backend/domain/temperature/service/TemperatureService.java
- src/main/java/ohsoontaxi/backend/domain/temperature/service/TemperatureUtils.java
- src/main/java/ohsoontaxi/backend/domain/temperature/service/temperatureService.java
- src/main/java/ohsoontaxi/backend/global/error/exception/ErrorCode.java
- ReportService 생성
-  TemperatureService 이름 수정 및 생성
> :pencil2:: TemperatureService 이름 수정 (#16)

- src/main/java/ohsoontaxi/backend/domain/temperature/domain/Temperature.java
- src/main/java/ohsoontaxi/backend/domain/temperature/domain/vo/TemperatureInfoVo.java
- src/main/java/ohsoontaxi/backend/domain/temperature/service/TemperatureService.java
- src/main/java/ohsoontaxi/backend/domain/temperature/service/TemperatureUtils.java
> :sparkles:: 사용자 온도 기능 추가 (#17)

- src/main/java/ohsoontaxi/backend/BackendApplication.java
- src/main/java/ohsoontaxi/backend/domain/reservation/domain/Reservation.java
- src/main/java/ohsoontaxi/backend/domain/reservation/presentation/ReservationController.java
-BaseEntity 생성 
-Reservation 적용
> :page_facing_up:: BaseEntity 생성 (#19)

- src/main/java/ohsoontaxi/backend/domain/reservation/presentation/dto/request/UpdateReservationRequest.java
- src/main/java/ohsoontaxi/backend/domain/reservation/presentation/dto/response/ReservationResponse.java
- src/main/java/ohsoontaxi/backend/domain/reservation/service/ReservationService.java
- src/main/java/ohsoontaxi/backend/domain/reservation/service/dto/UpdateReservationDto.java
- 방 업데이트 기능 수정 
- ReservationResponse 수정
> :art:: 방 업데이트 기능 수정 (#20)

- src/main/java/ohsoontaxi/backend/domain/reservation/presentation/dto/response/KeywordDto.java
> :page_facing_up:: keyword dto 생성 (#24)

- src/main/java/ohsoontaxi/backend/domain/reservation/domain/repository/ReservationRepository.java
- src/main/java/ohsoontaxi/backend/domain/reservation/domain/repository/ReservationRepositoryCustom.java
- src/main/java/ohsoontaxi/backend/domain/reservation/domain/repository/ReservationRepositoryImpl.java
- src/main/java/ohsoontaxi/backend/domain/reservation/presentation/ReservationController.java
- src/main/java/ohsoontaxi/backend/domain/reservation/service/ReservationService.java
- reservationRepositoryCustom 생성
- 키워드 검색 기능 추가 
-  키원드 추천 기능 추가
-  키원드 추천 기능 추가
> 🎨: 검색기능 추가 (#27)

- src/main/java/ohsoontaxi/backend/domain/asset/domain/ProfileImage.java
- src/main/java/ohsoontaxi/backend/domain/asset/service/AssetService.java
- src/main/java/ohsoontaxi/backend/domain/asset/service/AssetUtils.java
- src/main/java/ohsoontaxi/backend/domain/image/presentation/ImageController.java
- src/main/java/ohsoontaxi/backend/domain/user/domain/User.java
- src/main/java/ohsoontaxi/backend/domain/user/domain/vo/UserInfoVO.java
- src/main/java/ohsoontaxi/backend/domain/user/presentation/UserController.java
- src/main/java/ohsoontaxi/backend/domain/user/presentation/dto/response/UserProfileResponse.java
- src/main/java/ohsoontaxi/backend/domain/user/service/UserService.java
- src/main/java/ohsoontaxi/backend/global/init/InitDb.java
- 유저 기본 이미지로 다시 변경 로직
- 유저 온도 이미지 넣기
> :art:: 유저 로직 수정 (#29)

- src/main/java/ohsoontaxi/backend/domain/asset/domain/ProfileImage.java
- src/main/java/ohsoontaxi/backend/domain/asset/presentation/AssetController.java
- src/main/java/ohsoontaxi/backend/domain/asset/service/AssetService.java
- src/main/java/ohsoontaxi/backend/domain/asset/service/AssetUtils.java
- src/main/java/ohsoontaxi/backend/domain/user/domain/repository/UserRepository.java
- src/main/java/ohsoontaxi/backend/domain/user/service/UserService.java
- src/main/java/ohsoontaxi/backend/global/init/InitDb.java
> :art:: 유저 프로필 사진 로직 수정 (#34)

- build.gradle
- src/main/java/ohsoontaxi/backend/domain/credential/domain/RefreshTokenRedisEntity.java
- src/main/java/ohsoontaxi/backend/domain/credential/domain/repository/RefreshTokenRedisEntityRepository.java
- src/main/java/ohsoontaxi/backend/global/config/RedisCacheConfig.java
- src/main/java/ohsoontaxi/backend/global/config/RedisConfig.java
> :art:: redis 관련 기능 (#35)

- src/main/java/ohsoontaxi/backend/global/api/FeignConfiguration.java
- src/main/java/ohsoontaxi/backend/global/api/client/GoogleAuthClient.java
- src/main/java/ohsoontaxi/backend/global/api/client/KakaoOauthClient.java
- src/main/java/ohsoontaxi/backend/global/api/dto/OIDCPublicKeyDto.java
- src/main/java/ohsoontaxi/backend/global/api/dto/OIDCPublicKeysResponse.java
- kakao, google 공개키 목록 요청
- redis 캐시로 관리
> :art:: openFeign 관련 기능 (#36)

- src/main/java/ohsoontaxi/backend/domain/credential/presentation/CredentialController.java
- src/main/java/ohsoontaxi/backend/domain/credential/presentation/dto/request/RegisterRequest.java
- src/main/java/ohsoontaxi/backend/domain/credential/presentation/dto/request/TokenRefreshRequest.java
- src/main/java/ohsoontaxi/backend/domain/credential/presentation/dto/response/AuthTokensResponse.java
- src/main/java/ohsoontaxi/backend/domain/credential/presentation/dto/response/AvailableRegisterResponse.java
- src/main/java/ohsoontaxi/backend/domain/credential/service/CredentialService.java
- src/main/java/ohsoontaxi/backend/domain/credential/service/GoogleOauthStrategy.java
- src/main/java/ohsoontaxi/backend/domain/credential/service/KaKaoOauthStrategy.java
- src/main/java/ohsoontaxi/backend/domain/credential/service/OIDCDecodePayload.java
- src/main/java/ohsoontaxi/backend/domain/credential/service/OauthFactory.java
- src/main/java/ohsoontaxi/backend/domain/credential/service/OauthOIDCProvider.java
- src/main/java/ohsoontaxi/backend/domain/credential/service/OauthProvider.java
- src/main/java/ohsoontaxi/backend/domain/credential/service/OauthStrategy.java
- src/main/java/ohsoontaxi/backend/global/config/ConfigurationPropertiesConfig.java
- src/main/java/ohsoontaxi/backend/global/config/SecurityConfig.java
- src/main/java/ohsoontaxi/backend/global/property/OauthProperties.java
- src/main/java/ohsoontaxi/backend/global/security/JwtOIDCProvider.java
- src/main/resources/application.yml
- OIDC를 사용한 소셜 로그인 구현
- idToken 검증 로직 구현
- 회원가입 로직 구현
- 로그인 로직 구현
- refreshToken Refresh 로직 구현
- 로그 아웃 로직 구현
> :art:: 소셜 로그인 구현(kakao, google) (#36)
